version: '3.3'
services:
  postgres:
    image: postgres:11-alpine
    hostname: postgres
    ports:
      - "5433:5432"
    env_file:
      - ./.env
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d
  crescent:
    build:
      dockerfile: crescent/Dockerfile
      context: .
    command: bash -c "
      busybox crond -f -L /dev/stderr &
      python manage.py twitter_stream &
      daphne -b 0.0.0.0 -p 8080 project.asgi:fastapp &
      daphne -b 0.0.0.0 -p 8081 project.asgi:application"
    env_file:
      - ./.env
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
    volumes:
      - ./crescent:/opt/crescent
volumes:
  dbdata:
