# Generated by Django 3.0.8 on 2020-08-15 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='markov',
            unique_together={('prefix1', 'prefix2', 'suffix')},
        ),
    ]
